name: Run Unit Test and Build

on:
  push:
    branches:
      - '**'

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install dependencies
        run: go mod tidy

      - name: Run Unit Tests
        run: go test ./... -coverprofile=coverage.out
  build-docker-image:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install dependencies
        run: go mod tidy

      - name: Build Docker Image
        run: |
          docker build -t bank-statement-backend:latest .